[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Compiler settings
solc = "0.8.33"
optimizer = true
optimizer_runs = 200

[fmt]
sort_imports = true

[profile.ci]
deny_warnings = true
fuzz.seed = '0'
